language: node_js
node_js:
  - "0.12"
  - "lts/argon"
  - "lts/boron"
  - "7"

sudo: false
dist: trusty

cache:
  yarn: true

before_install:
  - "npm config set spin false"

install:
  - npm install

script:
  - npm run test:all

before_deploy:
  - npm install --global auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: MGME3tiODyEWOdBlWDXJW8pYbN8Ltz8rgnWSqthv5nCY/oN1SVm0mUOvGydCgoHxtszqUpvfExoBmnD/tcaXXVSzajfAWsa+DDx3zKvAcAbsNRsmPgBuWV8/Ptpq6bglx8kwGHeCatqQgghv0Mm7UrpMEZwbq3u7pzAVjNnUeSo=
  skip_cleanup: true
  on:
    tags: true
    repo: babel/broccoli-babel-transpiler
